[
    {
        "title": "The Legend of Zelda",
        "category": "Classic",
        "console": "NES",
        "platform": "HomeConsole",
        "releaseYear": 1986,
        "description": "L'inizio della leggenda. Un'avventura non lineare che ha definito il genere action-adventure.",
        "story": "Il regno di Hyrule è nel caos dopo che Ganon, il Re del Male, ha rubato la Triforza del Potere. La Principessa Zelda divide la Triforza della Saggezza in otto frammenti e li nasconde prima di essere catturata. Un giovane coraggioso di nome Link dovrà ritrovarli per sconfiggere Ganon.",
        "image": "/z1.jpg",
        "vote": 85,
        "remake": true,
        "remakePlatform": "Game & Watch / Switch Online",
        "id": 1,
        "createdAt": "2026-04-16T15:07:42.218Z",
        "updatedAt": "2026-04-16T15:07:42.218Z"
    },
    {
        "title": "Zelda II: The Adventure of Link",
        "category": "Side-scrolling",
        "console": "NES",
        "platform": "HomeConsole",
        "releaseYear": 1987,
        "description": "Un capitolo sperimentale con visuale laterale, combattimenti tecnici e una progressione a livelli tipica degli RPG.",
        "story": "Sei anni dopo la sconfitta di Ganon, Link nota uno strano marchio sul dorso della mano. Scopre che la Zelda originale è caduta in un sonno eterno a causa di un incantesimo. Link deve viaggiare verso il Grande Tempio per ottenere la Triforza del Coraggio e risvegliarla.",
        "image": "/z2.jpg",
        "vote": 70,
        "remake": false,
        "remakePlatform": "",
        "id": 2,
        "createdAt": "2026-04-16T15:08:17.977Z",
        "updatedAt": "2026-04-16T15:08:17.977Z"
    },
    {
        "title": "A Link to the Past",
        "category": "Classic",
        "console": "SNES",
        "platform": "HomeConsole",
        "releaseYear": 1991,
        "description": "Il perfezionamento della formula classica 2D, con l'introduzione dell'iconico passaggio tra il Mondo della Luce e il Mondo Oscuro.",
        "story": "Link viene svegliato da un messaggio telepatico della Principessa Zelda, prigioniera nel castello. Dopo la morte di suo zio, Link eredita la spada e lo scudo per fermare lo stregone Agahnim, che intende rompere il sigillo che tiene prigioniero Ganon nel Mondo Oscuro.",
        "image": "past.webp",
        "vote": 95,
        "remake": false,
        "remakePlatform": "",
        "id": 3,
        "createdAt": "2026-04-16T15:11:54.467Z",
        "updatedAt": "2026-04-16T15:11:54.467Z"
    },
    {
        "title": "Link's Awakening",
        "category": "Classic",
        "console": "GameBoy",
        "platform": "Portable",
        "releaseYear": 1993,
        "description": "Un'avventura onirica e malinconica fuori dal regno di Hyrule, famosa per i suoi personaggi bizzarri e i cameo Nintendo.",
        "story": "Dopo una tempesta in mare, Link naufraga sulle rive dell'isola di Koholint. Un gufo misterioso gli rivela che per lasciare l'isola deve recuperare gli otto strumenti delle Sirene e svegliare il leggendario Pesce Vento, che dorme in un uovo gigante sulla cima del monte.",
        "image": "link.png",
        "vote": 90,
        "remake": true,
        "remakePlatform": "Nintendo Switch",
        "id": 4,
        "createdAt": "2026-04-16T15:12:09.948Z",
        "updatedAt": "2026-04-16T15:12:09.948Z"
    },
    {
        "title": "Ocarina of Time",
        "category": "Action 3D",
        "console": "Nintendo 64",
        "platform": "HomeConsole",
        "releaseYear": 1998,
        "description": "Il capolavoro che ha definito il passaggio al 3D, introducendo il sistema di puntamento Z-target e un mondo esplorabile a cavallo.",
        "story": "Il giovane Link, un abitante della foresta, viene chiamato dal Grande Albero Deku. Per fermare il malvagio Ganondorf, Link dovrà viaggiare nel tempo, risvegliare i Saggi e reclamare la leggendaria Master Sword per salvare il futuro.",
        "image": "ocarina.png",
        "vote": 99,
        "remake": true,
        "remakePlatform": "Nintendo 3DS",
        "id": 5,
        "createdAt": "2026-04-16T15:15:00.831Z",
        "updatedAt": "2026-04-16T15:15:00.831Z"
    },
    {
        "title": "Majora's Mask",
        "category": "Action 3D",
        "console": "Nintendo 64",
        "platform": "HomeConsole",
        "releaseYear": 2000,
        "description": "Uno Zelda atipico e psicologico, basato sull'uso di maschere trasformanti e un ciclo continuo di tre giorni.",
        "story": "Mentre cerca un vecchio amico, Link viene trascinato nel mondo parallelo di Termina da uno Skull Kid posseduto dalla Maschera di Majora. Ha solo tre giorni prima che la Luna si schianti sulla terra: dovrà rivivere lo stesso tempo ripetutamente per trovare una soluzione.",
        "image": "majora.jpg",
        "vote": 92,
        "remake": true,
        "remakePlatform": "Nintendo 3DS",
        "id": 6,
        "createdAt": "2026-04-16T15:15:13.279Z",
        "updatedAt": "2026-04-16T15:15:13.279Z"
    },
    {
        "title": "Oracle of Ages",
        "category": "Classic",
        "console": "GameBoy",
        "platform": "Portable",
        "releaseYear": 2001,
        "description": "Focalizzato sugli enigmi ambientali e sulla manipolazione delle ere temporali per cambiare il presente.",
        "story": "Link viene trasportato nel regno di Labrynna, dove la sacerdotessa dell'ombra, Veran, possiede il corpo di Nayru, l'Oracolo delle Età. Veran viaggia nel passato per cambiare il corso della storia e Link deve inseguirla attraverso il tempo per ristabilire l'ordine.",
        "image": "ages.jpg",
        "vote": 88,
        "remake": false,
        "remakePlatform": "",
        "id": 7,
        "createdAt": "2026-04-16T15:15:24.610Z",
        "updatedAt": "2026-04-16T15:15:24.610Z"
    },
    {
        "title": "Oracle of Seasons",
        "category": "Classic",
        "console": "GameBoy",
        "platform": "Portable",
        "releaseYear": 2001,
        "description": "Un capitolo votato all'azione pura dove il gameplay ruota attorno al cambio magico delle stagioni.",
        "story": "Nel regno di Holodrum, il generale Onox rapisce Din, l'Oracolo delle Stagioni, facendo sprofondare il clima nel caos. Grazie allo Scettro delle Stagioni, Link deve alternare inverno, primavera, estate e autunno per farsi strada e salvare Din.",
        "image": "seasons.jpg",
        "vote": 88,
        "remake": false,
        "remakePlatform": "",
        "id": 8,
        "createdAt": "2026-04-16T15:15:40.635Z",
        "updatedAt": "2026-04-16T15:15:40.635Z"
    },
    {
        "title": "Four Swords",
        "category": "Classic",
        "console": "GameBoy",
        "platform": "Portable",
        "releaseYear": 2002,
        "description": "Un'esperienza multiplayer frenetica basata sulla cooperazione e la competizione tra quattro Link colorati.",
        "story": "Il mago del vento Vaati fugge dalla sua prigione nella Spada Quadrupla e rapisce Zelda. Link impugna la spada magica, dividendosi in quattro copie di se stesso, per superare dungeon che richiedono il lavoro di squadra per essere risolti.",
        "image": "4swords.jpg",
        "vote": 75,
        "remake": false,
        "remakePlatform": "",
        "id": 9,
        "createdAt": "2026-04-16T15:15:52.155Z",
        "updatedAt": "2026-04-16T15:15:52.155Z"
    },
    {
        "title": "The Wind Waker",
        "category": "Action 3D",
        "console": "GameCube",
        "platform": "HomeConsole",
        "releaseYear": 2002,
        "description": "Un'avventura marittima con uno stile grafico intramontabile e una forte enfasi sull'esplorazione navale.",
        "story": "In un mondo sommerso dalle acque, il giovane Link parte dall'Isola Primula per salvare sua sorella rapita da un uccello gigante. Scoprirà di essere l'Erede del Vento e dovrà solcare l'Oceano per riscoprire i segreti di una Hyrule dimenticata sotto le onde.",
        "image": "/wind.webp",
        "vote": 94,
        "remake": true,
        "remakePlatform": "Wii U",
        "id": 10,
        "createdAt": "2026-04-16T15:16:03.663Z",
        "updatedAt": "2026-04-16T15:16:03.663Z"
    },
    {
        "title": "Four Swords Adventures",
        "category": "Classic",
        "console": "GameCube",
        "platform": "HomeConsole",
        "releaseYear": 2004,
        "description": "Evolve la formula multiplayer unendo l'azione su TV alla gestione dell'inventario su GameBoy Advance.",
        "story": "Ombra Link inganna il vero Link spingendolo a estrarre la Spada Quadrupla, liberando nuovamente Vaati. I quattro Link devono viaggiare attraverso Hyrule per recuperare le Gocce di Forza e impedire che il mondo cada sotto l'oscurità eterna.",
        "image": "/adventure.jpg",
        "vote": 80,
        "remake": false,
        "remakePlatform": "",
        "id": 11,
        "createdAt": "2026-04-16T15:16:14.594Z",
        "updatedAt": "2026-04-16T15:16:14.594Z"
    },
    {
        "title": "The Minish Cap",
        "category": "Classic",
        "console": "GameBoy",
        "platform": "Portable",
        "releaseYear": 2004,
        "description": "Un gioiello 2D che gioca con le dimensioni, permettendo di esplorare il mondo da una prospettiva minuscola.",
        "story": "Vaati trasforma la Principessa Zelda in pietra durante un festival. Link incontra Ezero, un cappello magico parlante che gli permette di rimpicciolirsi alle dimensioni dei Minish, un popolo di folletti che potrebbe avere la chiave per spezzare la maledizione.",
        "image": "/minish.jpg",
        "vote": 89,
        "remake": false,
        "remakePlatform": "",
        "id": 12,
        "createdAt": "2026-04-16T15:16:27.305Z",
        "updatedAt": "2026-04-16T15:16:27.305Z"
    },
    {
        "title": "Twilight Princess",
        "category": "Action 3D",
        "console": "Wii",
        "platform": "HomeConsole",
        "releaseYear": 2006,
        "description": "Un'avventura epica dai toni maturi e oscuri, caratterizzata dalla trasformazione in lupo e dal Regno del Crepuscolo.",
        "story": "Hyrule viene invasa dal Crepuscolo, una dimensione d'ombra che trasforma gli abitanti in spiriti. Link, trasformato in lupo, unisce le forze con l'enigmatica Midna per cacciare l'usurpatore Zant e impedire che l'ombra divori la luce per sempre.",
        "image": "/ligth.webp",
        "vote": 93,
        "remake": true,
        "remakePlatform": "Wii U",
        "id": 13,
        "createdAt": "2026-04-16T15:16:36.213Z",
        "updatedAt": "2026-04-16T15:16:36.213Z"
    },
    {
        "title": "Phantom Hourglass",
        "category": "Classic",
        "console": "Nintendo DS",
        "platform": "Portable",
        "releaseYear": 2007,
        "description": "Il primo capitolo per DS che sfrutta interamente il pennino per muoversi, attaccare e tracciare rotte nautiche.",
        "story": "Seguito diretto di Wind Waker. Dopo che Dazel scompare a bordo di una nave fantasma, Link si ritrova su un'isola sconosciuta. Insieme al capitano Linebeck, dovrà esplorare il Tempio del Re Marittimo usando la Clessidra Illusione per sfuggire al tempo.",
        "image": "/phantom.jpg",
        "vote": 82,
        "remake": false,
        "remakePlatform": "",
        "id": 14,
        "createdAt": "2026-04-16T15:16:47.075Z",
        "updatedAt": "2026-04-16T15:16:47.075Z"
    },
    {
        "title": "Spirit Tracks",
        "category": "Classic",
        "console": "Nintendo DS",
        "platform": "Portable",
        "releaseYear": 2009,
        "description": "Sostituisce la barca con un treno a vapore personalizzabile e introduce una Zelda spirito che combatte al fianco di Link.",
        "story": "In una nuova Hyrule, le ferrovie magiche che fungono da catene per un antico demone stanno scomparendo. Quando il corpo di Zelda viene rubato dal malvagio Primo Ministro, il suo spirito si unisce a Link per riparare le rotaie e recuperare le sue spoglie.",
        "image": "/spirit.jpg",
        "vote": 81,
        "remake": false,
        "remakePlatform": "",
        "id": 15,
        "createdAt": "2026-04-16T15:17:06.654Z",
        "updatedAt": "2026-04-16T15:17:06.654Z"
    },
    {
        "title": "Skyward Sword",
        "category": "Action 3D",
        "console": "Wii",
        "platform": "HomeConsole",
        "releaseYear": 2011,
        "description": "L'origine della cronologia. Introduce il volo sopra le nuvole e un sistema di combattimento 1:1 con i sensori di movimento.",
        "story": "Link e Zelda vivono a Oltrenuvola, un'isola sospesa nel cielo. Quando Zelda cade sotto lo strato di nubi, Link scopre la Spada della Dea e scende nel misterioso mondo sottostante per salvarla, scoprendo il destino eterno che lega lui, lei e il male.",
        "image": "/skyward.jpg",
        "vote": 87,
        "remake": true,
        "remakePlatform": "Nintendo Switch",
        "id": 16,
        "createdAt": "2026-04-16T15:17:24.395Z",
        "updatedAt": "2026-04-16T15:17:24.395Z"
    },
    {
        "title": "A Link Between Worlds",
        "category": "Classic",
        "console": "Nintendo 3DS",
        "platform": "Portable",
        "releaseYear": 2013,
        "description": "Rivisita la mappa di A Link to the Past aggiungendo la meccanica del diventare un dipinto sui muri.",
        "story": "Lo stregone Yuga sta intrappolando i discendenti dei Saggi in dei quadri. Link ottiene il potere di fondersi con le pareti come un disegno, permettendogli di viaggiare tra Hyrule e il suo riflesso oscuro, il regno decadente di Lorule.",
        "image": "between.jpg",
        "vote": 91,
        "remake": false,
        "remakePlatform": "",
        "id": 17,
        "createdAt": "2026-04-16T15:17:33.873Z",
        "updatedAt": "2026-04-16T15:17:33.873Z"
    },
    {
        "title": "Tri Force Heroes",
        "category": "Classic",
        "console": "Nintendo 3DS",
        "platform": "Portable",
        "releaseYear": 2015,
        "description": "Uno spin-off cooperativo dove tre giocatori creano totem umani e cambiano abiti per ottenere poteri speciali.",
        "story": "Nel regno di Hytopia, fissato con la moda, la principessa viene maledetta da una strega a indossare una calzamaglia orrenda. Link e altri due eroi partono per le Terre Esterne per sconfiggere la strega e recuperare lo stile del regno.",
        "image": "/triforce.jpg",
        "vote": 73,
        "remake": false,
        "remakePlatform": "",
        "id": 18,
        "createdAt": "2026-04-16T15:17:53.859Z",
        "updatedAt": "2026-04-16T15:17:53.859Z"
    },
    {
        "title": "Breath of the Wild",
        "category": "Open Air",
        "console": "Switch",
        "platform": "Hybrid",
        "releaseYear": 2017,
        "description": "Il primo titolo openworld della serie, che ha rivoluzionato il genere con un gameplay basato sulla fisica e un'esplorazione totale.",
        "story": "Link si risveglia in una caverna dopo 100 anni di sonno, chiamato da una voce misteriosa. Si ritrova in una terra desolata, minacciata da una Calamità che sta consumando il regno di Hyrule. A chi appartiene quella voce? Cosa è successo 100 anni fa?",
        "image": "/botw.jpg",
        "vote": 97,
        "remake": false,
        "remakePlatform": "",
        "id": 19,
        "createdAt": "2026-04-16T15:18:05.843Z",
        "updatedAt": "2026-04-16T15:18:05.843Z"
    },
    {
        "title": "Tears of the Kingdom",
        "category": "Open Air",
        "console": "Switch",
        "platform": "Hybrid",
        "releaseYear": 2023,
        "description": "Espande i confini di Hyrule verso il cielo e il sottosuolo, introducendo un rivoluzionario sistema di costruzione.",
        "story": "Dopo il risveglio di una mummia malevola sotto il castello, Zelda scompare e Link perde il suo braccio. Risvegliatosi su un'isola nel cielo con un nuovo braccio magico, Link deve ricostruire il passato e cercare Zelda in una Hyrule stravolta da isole celesti e abissi profondi.",
        "image": "/tears.jpg",
        "vote": 96,
        "remake": false,
        "remakePlatform": "",
        "id": 20,
        "createdAt": "2026-04-16T15:18:15.428Z",
        "updatedAt": "2026-04-16T15:18:15.428Z"
    },
    {
        "title": "Echoes of Wisdom",
        "category": "Classic",
        "console": "Switch",
        "platform": "Hybrid",
        "releaseYear": 2024,
        "description": "Per la prima volta Zelda è protagonista assoluta, con un gameplay basato sulla creazione di repliche magiche degli oggetti.",
        "story": "Strani squarci stanno inghiottendo gli abitanti di Hyrule, incluso Link. La Principessa Zelda, rimasta sola, incontra lo spirito Tri e riceve il bastone magico che le permette di creare 'eco' di tutto ciò che incontra per salvare il suo regno e l'eroe prigioniero.",
        "image": "/windsom.avif",
        "vote": 86,
        "remake": false,
        "remakePlatform": "",
        "id": 21,
        "createdAt": "2026-04-16T15:18:25.196Z",
        "updatedAt": "2026-04-16T15:18:25.196Z"
    }
]